- hosts: all
  become: true
  tasks:
    - name: Upgrade all packages to the latest version
      apt:
        name: '*'
        state: latest
        update_cache: true

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker APT repository
      apt_repository:
        repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'
        state: present
        filename: 'docker'

    - name: Install Docker and Docker Compose
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose
          - python3-pip
          - python3-venv
        state: present
        update_cache: true

    - name: Start and enable Docker
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Run whoami without become
      command: whoami
      changed_when: false
      become: false
      register: whoami

    - name: Set a fact with the user name
      set_fact:
        login_user: '{{ whoami.stdout }}'

    - name: Add the current user to 'docker' group
      user:
        name: '{{ whoami.stdout }}'
        groups: docker
        append: yes

    - name: Reset SSH connection to refresh user groups
      meta: reset_connection
