version: "3.3"

services:
  agent:
    image: portainer/agent:2.20.3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global

  portainer:
    image: portainer/portainer-ce:2.20.3
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - "9000:9000"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik_web
      - agent_network
    deploy:
      mode: replicated  # Используйте replicated вместо global для лучшего управления
      replicas: 1       # Один экземпляр Portainer на все менеджеры
      placement:
        constraints: [node.role == manager]
    labels:
      - "traefik.enable=true"                                                # Включает Traefik для этого контейнера
      - "traefik.http.routers.portainer.rule=Host(`portainer.example.com`)"  # Маршрутизирует запросы на домен `portainer.example.com`
      - "traefik.http.routers.portainer.entrypoints=web"                     # Использует точку входа `web` (HTTP, порт 80)
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"      # Направляет трафик на порт 9000 внутри контейнера
      - "traefik.http.routers.portainer.service=portainer"                   # Указывает, что маршрутизатор portainer будет направлять запросы к сервису portainer

volumes:
  portainer_data:

networks:
  traefik_web:
    external: true
  agent_network:
    driver: overlay
    attachable: true
